"""Orthogonal semantic action facets."""

from enum import StrEnum


class ActionIntent(StrEnum):
    KEEP_CORE = "KEEP_CORE"
    ACTIVATE_REGISTERED_STAGE = "ACTIVATE_REGISTERED_STAGE"
    REDUCE_TACTICAL = "REDUCE_TACTICAL"
    PARTIAL_PROFIT = "PARTIAL_PROFIT"
    EXIT_STRATEGIC = "EXIT_STRATEGIC"
    EXIT_TO_REENTRY_PENDING = "EXIT_TO_REENTRY_PENDING"
    REENTER_PARTIAL = "REENTER_PARTIAL"
    NO_ACTION_WITH_OBLIGATION = "NO_ACTION_WITH_OBLIGATION"


class ProtectiveActionType(StrEnum):
    NONE = "NONE"
    TIGHTEN_STOP = "TIGHTEN_STOP"
    TRAIL_CORE = "TRAIL_CORE"
    STOP = "STOP"
    KILL = "KILL"
    PROTECTION_REPAIR = "PROTECTION_REPAIR"
    REDUCE_ONLY = "REDUCE_ONLY"
    EXIT = "EXIT"
    TIMEOUT = "TIMEOUT"
    RECONCILIATION = "RECONCILIATION"


class GeometryOperation(StrEnum):
    KEEP = "KEEP"
    EXPIRE = "EXPIRE"
    REBUILD_ANALYTICAL = "REBUILD_ANALYTICAL"
    REVISE_PROTECTION = "REVISE_PROTECTION"

